#!/usr/bin/env Rscript
args = commandArgs(trailingOnly=TRUE)
far <- scan("fingerprint/true/far.txt")
frr <- scan("fingerprint/true/frr.txt")
pdf(file="roc.pdf")
par(mgp=c(2.2,0.45,0), tcl=-0.4, mar=c(3.3,3.3,3.3,1.1))
plot(far, 1 - frr, xlab="FAR", ylab="1 - FRR", col="blue", pch=16, type="l", xaxs="i", yaxs="i")
par(new = TRUE)
far <- scan("fingerprint/automatic/far.txt")
frr <- scan("fingerprint/automatic/frr.txt")
plot(far, 1 - frr, type='l', pch=16, col="red", axes = FALSE, ann = FALSE, xaxs="i", yaxs="i")
par(new = TRUE)
far <- scan("iris/solo/far.txt")
frr <- scan("iris/solo/frr.txt")
plot(far, 1 - frr, type='l', pch=16, col="darkgreen", axes = FALSE, ann = FALSE, xaxs="i", yaxs="i")
par(new = TRUE)
far <- scan("iris/and_fingerprint/far.txt")
frr <- scan("iris/and_fingerprint/frr.txt")
plot(far, 1 - frr, type='l', pch=16, col="green", axes = FALSE, ann = FALSE, xaxs="i", yaxs="i")
par(new = TRUE)
plot(c(0:1.0), c(0:1.0), type='l', pch=16, col="black", lty = 5, axes = FALSE, ann = FALSE, xaxs="i", yaxs="i")
legend("bottomright", inset=.05, cex = 1, c("Impressão digital - detecção manual", "Impressão digital - detecção automática", "Iris - detecção manual", "Iris + Impressão digital - manual", "Aleatório"), lty=c(1,1,1,1,5), lwd=c(2,2,2,2,2), col=c("blue", "red", "darkgreen", "green", "black"), bg="grey96")
grid(col = "lightgray", lty = "dotted", lwd = par("lwd"), equilogs = TRUE)
dev.off()
