#!/usr/bin/env Rscript
graph_data <- read.table("true-automatic-fdr.txt", header=T, sep="\t")
pdf(file="detection.pdf")
par(mgp=c(2.2,0.45,0), tcl=-0.4, mar=c(3.3,2.5,3.3,1.1))
plot(graph_data$thr, graph_data$fdr, type='l', pch=16, col='red', xlim=range(0:80), ylim=range(0:1), ann=FALSE, xaxs="i", yaxs="i")
par(new = TRUE)
graph_data <- read.table("true-automatic-fndr.txt", header=T, sep="\t")
plot(graph_data$thr, graph_data$fndr, type='l', pch=16, col=rgb(0, 150, 0, maxColorValue=255), xlim=range(0:80), ylim=range(0:1), axes = FALSE, ann = FALSE, xaxs="i", yaxs="i")
grid(col = "lightgray", lty = "dotted", lwd = par("lwd"), equilogs = TRUE)
legend("bottomright", inset=.05, cex = 1, c("FDR", "DR"), lty=c(1,1), lwd=c(2,2), col=c("red",rgb(0, 150, 0, maxColorValue=255)), bg="grey96")
title(main="", xlab=substitute(paste("Distância máxima entre correspondências (em ", italic('pixels'), ")" )), ylab="")
dev.off()
